### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by Aloso** [LeoTuet/ui-we-want-to-sleep#84]
Some things don't look as desired in dark mode.

### Home page
![2022-03-28 09_57_06-we wantToSleep()](https://user-images.githubusercontent.com/15658558/160352788-d27f1da6-7315-426a-bd5e-5f681ef47f80.png)

The star sky is visible in the content section, not just the heading.

### Legal
![2022-03-28 09_56_16-we wantToSleep()](https://user-images.githubusercontent.com/15658558/160352836-814bb63e-9689-42ff-8c3d-df6960e6114e.png)

The headings appear on top of the nav. This is visible because the text is white in dark mode.

In Firefox, the headings also aren't sticky.

**Comment by Aloso** [comment]
I managed to fix the issues with the legal page with this CSS:

```css
.legalBackground {
    z-index: 0;
    position: relative;
}

.legalSection {
    align-items: flex-start;
}

.stickyHeader {
    z-index: 1;
    margin-bottom: 1em;
}
```

I might be too busy today to send a PR.
